### ISSUE TITLE
CRX3 format

### ISSUE THREAD

**Issue by xt0rted** [silverwind/fetch-css#3]
Just started getting the following error while trying to regenerate github dark. It was working a few hours ago. All of the other extensions are working, just not this one.

The extension is still in the store too but it's not downloading and causes the process to crash so generation doesn't complete.

https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

```
❯ npm run generate

> github-dark@2.0.84 generate C:\dev\GitHub\GitHub-Dark
> node tools/generate.js && npm run clean

(fetch-css) Warning: Failed to fetch https://clients2.google.com/service/update2/crx?response=redirect&prodversion=83.0&x=id%3Dhlepfoohegkhhmjieoechaddaejaokhf%26installsource%3Dondemand%26uc: 204 No Content
Unhandled rejection Error: FILE_ENDED
    at PullStream.pull (C:\dev\GitHub\GitHub-Dark\node_modules\unzipper\lib\PullStream.js:83:28)
    at PullStream.emit (events.js:315:20)
    at PullStream.<anonymous> (C:\dev\GitHub\GitHub-Dark\node_modules\unzipper\lib\PullStream.js:20:10)
    at PullStream.emit (events.js:327:22)
    at finishMaybe (_stream_writable.js:653:14)
    at endWritable (_stream_writable.js:670:3)
    at PullStream.Writable.end (_stream_writable.js:598:5)
    at PassThrough.onend (_stream_readable.js:673:10)
    at Object.onceWrapper (events.js:421:28)
    at PassThrough.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Error: FILE_ENDED
    at PullStream.pull (C:\dev\GitHub\GitHub-Dark\node_modules\unzipper\lib\PullStream.js:83:28)
    at PullStream.emit (events.js:315:20)
    at PullStream.<anonymous> (C:\dev\GitHub\GitHub-Dark\node_modules\unzipper\lib\PullStream.js:20:10)
    at PullStream.emit (events.js:327:22)
    at finishMaybe (_stream_writable.js:653:14)
    at endWritable (_stream_writable.js:670:3)
    at PullStream.Writable.end (_stream_writable.js:598:5)
    at PassThrough.onend (_stream_readable.js:673:10)
    at Object.onceWrapper (events.js:421:28)
    at PassThrough.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! github-dark@2.0.84 generate: `node tools/generate.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the github-dark@2.0.84 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\brian\AppData\Roaming\npm-cache\_logs\2020-05-21T23_56_09_565Z-debug.log
```

**Comment by xt0rted** [comment]
This version of the url downloads https://clients2.google.com/service/update2/crx?response=redirect&prodversion=83.0.4103.39&acceptformat=crx2,crx3&x=id%3Dhlepfoohegkhhmjieoechaddaejaokhf%26uc (includes the parameter `acceptformat=crx2,crx3`) but `PullStream.pull` still blows up.

**Comment by silverwind** [comment]
I get a 204 using `curl`. Maybe google changed the download URL or parameters? I can't really debug this in Chrome because devtools does not log the HTTP request for the `.crx` file.

**Comment by silverwind** [comment]
Maybe we need to add some hackery like https://github.com/Rob--W/crxviewer/blob/master/src/cws_pattern.js#L84.

**Comment by xt0rted** [comment]
That's how I got the working url. The `open` url in the top right https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Frefined-github%2Fhlepfoohegkhhmjieoechaddaejaokhf

**Comment by silverwind** [comment]
Ok it seems chrome store does no longer serve `crx2`, only `crx3` which unzipper can not handle.

**Comment by silverwind** [comment]
Opened https://github.com/ZJONSSON/node-unzipper/issues/196. 

Vendoring https://github.com/Rob--W/crxviewer/blob/master/src/lib/crx-to-zip.js in the meanwhile might be an option.

**Comment by silverwind** [comment]
Fixed in 3.0.1. Leaving this open as I'm not happy with shipping the crx extraction in this module. Either https://github.com/ZJONSSON/node-unzipper/issues/196 gets fixed or maybe someone publishes as standalone in-memory crx3 extraction module (there's none on npm).
